// Structured area/town list, keyed by state - used to drive the dependent
// "Area" dropdown on both the Post Listing and Post Buyer Requirement forms.
//
// This replaces free-text area entry so the matching engine (utils/matching.js)
// can compare areas exactly instead of guessing via substring matching -
// "PJ" vs "Petaling Jaya" never lined up as text, but as two selections from
// the same list they now do.
//
// Cross-checked against mudah.my's full location filter (Sep 2026) so every
// district/mukim/town mudah.my lists for property listings has an entry
// here too - not just a curated shortlist of well-known towns anymore.
// If an agent still needs a town that's missing, add it to the array below
// for that state - no other code changes required.

const AREAS_BY_STATE = {
  Johor: [
    "Johor Bahru",
    "Iskandar Puteri",
    "Nusajaya",
    "Skudai",
    "Kulai",
    "Pasir Gudang",
    "Kluang",
    "Batu Pahat",
    "Muar",
    "Segamat",
    "Pontian",
    "Kota Tinggi",
    "Mersing",
    "Tangkak",
    "Gelang Patah",
    "Ulu Tiram",
    "Ayer Baloi",
    "Ayer Hitam",
    "Bakri",
    "Batu Anam",
    "Bekok",
    "Benut",
    "Bukit Gambir",
    "Bukit Kangkar",
    "Buloh Kasap",
    "Bukit Pasir",
    "Bukit Serampang",
    "Chaah",
    "Endau",
    "Gemas Bahru",
    "Gerisek",
    "Gugusan Taib Andak",
    "Jementah",
    "Jeram Batu",
    "Kahang",
    "Kampung Kenangan Tun Dr Ismail",
    "Kukup",
    "Labis",
    "Layang Layang",
    "Masai",
    "Medini",
    "Niyor",
    "Horizon Hills",
    "Pagoh",
    "Paloh",
    "Panchor",
    "Parit Jawa",
    "Parit Raja",
    "Parit Sulong",
    "Pekan Nanas",
    "Pengerang",
    "Perling",
    "Permas Jaya",
    "Plentong",
    "Puteri Harbour",
    "Rengam",
    "Rengit",
    "Semerah",
    "Senai",
    "Senggarang",
    "Senibong",
    "Sedenak",
    "Sedili",
    "Serkat",
    "Serom",
    "Setia Indah",
    "Setia Tropika",
    "Simpang Renggam",
    "Sri Gading",
    "Sungai Mati",
    "Tampoi",
    "Tebrau",
    "Ulu Sungai Johor",
    "Yong Peng",
  ],
  Kedah: [
    "Alor Setar",
    "Sungai Petani",
    "Kulim",
    "Langkawi",
    "Jitra",
    "Baling",
    "Kuala Kedah",
    "Gurun",
    "Pendang",
    "Yan",
    "Lunas",
    "Sik",
    "Mergong",
    "Sungai Kob",
    "Padang Serai",
    "Alor Merah",
    "Anak Bukit",
    "Ayer Hitam",
    "Bandar Baharu",
    "Bukit Kayu Hitam",
    "Changlun",
    "Guar Chempedak",
    "Karangan",
    "Kepala Batas",
    "Kodiang",
    "Kota Sarang Semut",
    "Kota Setar",
    "Kuah",
    "Kuala Ketil",
    "Kuala Muda",
    "Kuala Nerang",
    "Kubang Pasu",
    "Kupang",
    "Merbok",
    "Naga Lilit",
    "Padang Matsirat",
    "Padang Meha",
    "Padang Terap",
    "Pokok Sena",
    "Pinang Tunggal",
    "Semeling",
    "Serdang",
    "Simpang Empat",
    "Sungai Lalang",
    "Sungai Pasir",
    "Tawar",
    "Tikam Batu",
    "Teloi Kiri",
    "Temin",
    "Ulu Melaka",
    "University Utara",
    "Bedong",
    "Langgar",
  ],
  Kelantan: [
    "Kota Bharu",
    "Pasir Mas",
    "Tanah Merah",
    "Machang",
    "Gua Musang",
    "Tumpat",
    "Kuala Krai",
    "Wakaf Bharu",
    "Pasir Puteh",
    "Ayer Lanas",
    "Bachok",
    "Badang",
    "Baung",
    "Cherang Ruku",
    "Dabong",
    "Jeli",
    "Kem Desa Pahlawan",
    "Kemumin",
    "Ketereh",
    "Kok Lanas",
    "Kuala Balah",
    "Kubang Kerian",
    "Melor",
    "Padang Enggang",
    "Pendek",
    "Pengkalan Chepa",
    "Peringat",
    "Pulai Chondong",
    "Rantau Panjang",
    "Selising",
    "Tawang",
    "Telok",
    "Temangan",
    "Tiong",
  ],
  "Kuala Lumpur": [
    "Bangsar",
    "Mont Kiara",
    "Sri Hartamas",
    "Damansara Heights",
    "KLCC",
    "Bukit Bintang",
    "Cheras",
    "Setapak",
    "Wangsa Maju",
    "Titiwangsa",
    "Sentul",
    "Kepong",
    "Bukit Jalil",
    "Sri Petaling",
    "Taman Desa",
    "Segambut",
    "Ampang Hilir",
    "Pantai",
    "Bandar Tun Razak",
    "Jinjang",
    "OUG (Old Klang Road)",
    "Bandar Damai Perdana",
    "Bandar Menjalara",
    "Bandar Tasik Selatan",
    "Bangsar South",
    "Batu",
    "Brickfields",
    "Bukit Kiara",
    "Bukit Ledang",
    "Bukit Persekutuan",
    "Bukit Tunku",
    "Chan Sow Lin",
    "City Centre",
    "Country Heights",
    "Country Heights Damansara",
    "Damansara",
    "Desa Pandan",
    "Desa ParkCity",
    "Desa Petaling",
    "Federal Hill",
    "Gombak",
    "Ampang",
    "Jalan Ipoh",
    "Jalan Kuching",
    "Jalan Sultan Ismail",
    "Kenny Hills",
    "Kampung Baru",
    "Keramat",
    "KL City",
    "KL Eco City",
    "KL Sentral",
    "Kuchai Lama",
    "Mid Valley City",
    "Old Klang Road",
    "OUG",
    "Pandan Indah",
    "Pandan Jaya",
    "Pandan Perdana",
    "Pekan Batu",
    "Puchong",
    "Pudu",
    "Salak Selatan",
    "Seputeh",
    "Serdang",
    "Setiawangsa",
    "Solaris Dutamas",
    "Sri Damansara",
    "Sungai Besi",
    "Sungai Penchala",
    "Sunway SPK",
    "Taman Duta",
    "Taman Melawati",
    "Taman Tun Dr Ismail",
    "Taman Permata",
    "TPM",
  ],
  Labuan: [
    "Bandar Labuan",
    "Victoria",
    "Rancha-Rancha",
    "Patau-Patau",
    "Batu Arang",
    "Batu Manikar",
    "Bebuloh",
    "Belukut",
    "Bukit Kalam",
    "Bukit Kuda",
    "Durian Tunjung",
    "Ganggarak / Merinding",
    "Gersik / Saguking / Jawa / Parit",
    "Kilan / Kilan Pulau Akar",
    "Lajau",
    "Layang-Layangan",
    "Lubok Temiang",
    "Nagalang / Kerupang",
    "Pantai",
    "Patau-Patau 1",
    "Patau-Patau 2",
    "Pohon Batu",
    "Sungai Bedaun",
    "Sungai Bangat",
    "Sungai Buton",
    "Sungai Keling",
    "Sungai Lada",
    "Sungai Labu",
    "Sungai Miri / Pagar",
    "Tanjung Aru",
  ],
  Melaka: [
    "Bandar Melaka",
    "Ayer Keroh",
    "Alor Gajah",
    "Jasin",
    "Batu Berendam",
    "Bukit Katil",
    "Klebang",
    "Tanjung Kling",
    "Masjid Tanah",
    "Alai",
    "Asahan",
    "Ayer Molek",
    "Bachang",
    "Balai Panjang",
    "Bandar Hilir",
    "Bemban",
    "Bertam",
    "Bertam Malim",
    "Bertam Ulu",
    "Bukit Baru",
    "Bukit Rambai",
    "Bukit Serindit",
    "Brisu",
    "Cheng",
    "Duyong",
    "Bukit Beruang",
    "Durian Tunggal",
    "Klebang Besar",
    "Krubong",
    "Kuala Linggi",
    "Kuala Sungai Baru",
    "Lendu",
    "Lubok China",
    "Machap",
    "Melaka City",
    "Melaka Jaya",
    "Melaka Raya",
    "Melaka Tengah",
    "Merlimau",
    "Paya Rumput",
    "Pegoh",
    "Pokok Mangga",
    "Pulau Gedong",
    "Pulau Melaka",
    "Pulau Sebang",
    "Rembia",
    "Selandar",
    "Semabok",
    "Serkam",
    "Simpang Ampat",
    "Sungai Rambai",
    "Sungei Baru Tengah",
    "Sungei Petai",
    "Sungai Udang",
    "Taman Asean",
    "Taman Malim Jaya",
    "Tanjong Minyak",
    "Telok Mas",
    "Ujong Pasir",
    "Umbai",
  ],
  "Negeri Sembilan": [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Bahau",
    "Kuala Pilah",
    "Rembau",
    "Tampin",
    "Mantin",
    "Ampangan",
    "Bandar Baru Enstek",
    "Bandar Baru Serting",
    "Bandar Sri Sendayan",
    "Batang Melaka",
    "Batu Kikir",
    "Bukit Kepayang",
    "Gemas",
    "Gemencheh",
    "Jelebu",
    "Jempol",
    "Jimah",
    "Johol",
    "Juasseh",
    "Kota",
    "Kuala Klawang",
    "Labu",
    "Lenggeng",
    "Linggi",
    "Lukut",
    "Pantai",
    "Paroi",
    "Pasir Panjang",
    "Pedas",
    "Rantau",
    "Rasah",
    "Rompin",
    "Senawang",
    "Seremban 2",
    "Sikamat",
    "Siliau",
    "Simpang Durian",
    "Simpang Pertang",
    "Sri Menanti",
    "Sri Rusa",
    "Tanjong Ipoh",
    "Telok Kemang",
    "Titi",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Raub",
    "Jerantut",
    "Cameron Highlands",
    "Genting Highlands",
    "Mentakab",
    "Pekan",
    "Kuala Lipis",
    "Balok",
    "Bandar Pusat Jengka",
    "Bandar Tun Abdul Razak",
    "Benta",
    "Bera",
    "Beserah",
    "Brinchang",
    "Bukit Fraser",
    "Chenor",
    "Daerah Rompin",
    "Damak",
    "Dong",
    "Gali",
    "Hulu Lepar",
    "Hulu Telom",
    "Karak",
    "Kuala Rompin",
    "Lanchang",
    "Lurah Bilut",
    "Maran",
    "Mengkarak",
    "Muadzam Shah",
    "Padang Tengku",
    "Penor",
    "Ringlet",
    "Rompin",
    "Sabai",
    "Sega",
    "Sungai Karang",
    "Sungai Koyan",
    "Sungai Lembing",
    "Sungai Ruan",
    "Tanah Rata",
    "Teras",
    "Triang",
  ],
  Perak: [
    "Ipoh",
    "Taiping",
    "Sitiawan",
    "Teluk Intan",
    "Lumut",
    "Batu Gajah",
    "Kampar",
    "Tapah",
    "Bidor",
    "Kuala Kangsar",
    "Manjung",
    "Gopeng",
    "Parit Buntar",
    "Ayer Tawar",
    "Bagan Datoh",
    "Bagan Serai",
    "Batu Kurau",
    "Behrang Stesen",
    "Beriah",
    "Beruas",
    "Bota",
    "Changkat Jering",
    "Changkat Keruing",
    "Chemor",
    "Chenderiang",
    "Chenderong Balai",
    "Chikus",
    "Enggor",
    "Gerik",
    "Hutan Melintang",
    "Intan",
    "Jeram",
    "Kampong Gajah",
    "Kampong Kepayang",
    "Kamunting",
    "Kerian",
    "Kuala Kurau",
    "Kuala Sepetang",
    "Lahat",
    "Lambor Kanan",
    "Langkap",
    "Lekir",
    "Lenggong",
    "Malim Nawar",
    "Mambang Diawan",
    "Manong",
    "Matang",
    "Menglembu",
    "Padang Rengas",
    "Pengkalan Baharu",
    "Pangkor",
    "Pantai Remis",
    "Parit",
    "Pengkalan Hulu",
    "Pusing",
    "Rantau Panjang",
    "Sauk",
    "Selama",
    "Selekoh",
    "Selinsing",
    "Semanggol",
    "Seri Manjong",
    "Seri Iskandar",
    "Simpang",
    "Simpang Pulai",
    "Slim River",
    "Sungai Siput",
    "Sungai Sumun",
    "Sungkai",
    "Tambun",
    "Tanjong Piandang",
    "Tanjong Rambutan",
    "Tanjong Tualang",
    "Tanjung Malim",
    "Tapah Road",
    "Temoh",
    "TLDM Lumut",
    "Trolak",
    "Trong",
    "Tronoh",
    "Ulu Bernam",
    "Ulu Kinta",
  ],
  Perlis: [
    "Kangar",
    "Arau",
    "Padang Besar",
    "Kuala Perlis",
    "Kaki Bukit",
    "Pauh",
    "Seriab",
    "Simpang Ampat",
    "Titi Tinggi",
    "Utan Aji",
  ],
  "Pulau Pinang": [
    "George Town",
    "Bayan Lepas",
    "Bukit Mertajam",
    "Butterworth",
    "Sungai Ara",
    "Tanjung Bungah",
    "Batu Ferringhi",
    "Air Itam",
    "Gelugor",
    "Simpang Ampat",
    "Nibong Tebal",
    "Balik Pulau",
    "Jelutong",
    "Bayan Baru",
    "Tasek Gelugor",
    "Air Tawar",
    "Alma",
    "Bagan Ajam",
    "Bagan Jermal",
    "Bagan Lalang",
    "Bandar Perda",
    "Batu Kawan",
    "Batu Maung",
    "Batu Uban",
    "Berapit",
    "Bertam",
    "Bukit Dumbar",
    "Bukit Jambul",
    "Bukit Minyak",
    "Bukit Tambun",
    "Bukit Tengah",
    "Gertak Sangul",
    "Greenlane",
    "Jawi",
    "Juru",
    "Kepala Batas",
    "Kubang Semang",
    "Mak Mandin",
    "Minden Heights",
    "Pauh Jaya",
    "Paya Terubong",
    "Penaga",
    "Penang Hill",
    "Penanti",
    "Perai",
    "Permatang Kuching",
    "Permatang Pauh",
    "Permatang Tinggi",
    "Persiaran Gurney",
    "Prai",
    "Pulau Betong",
    "Pulau Tikus",
    "Raja Uda",
    "Relau",
    "Scotland",
    "Seberang Jaya",
    "Seberang Perai",
    "Serdang",
    "Sungai Bakap",
    "Sungai Dua",
    "Sungai Jawi",
    "Sungai Nibong",
    "Sungai Pinang",
    "Tanjong Tokong",
    "Teluk Bahang",
    "Teluk Kumbar",
    "USM",
    "Valdor",
  ],
  Putrajaya: [
    "Precinct 1",
    "Precinct 8",
    "Precinct 9",
    "Precinct 11",
    "Precinct 14",
    "Precinct 16",
    "Precinct 18",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Penampang",
    "Putatan",
    "Papar",
    "Kudat",
    "Ranau",
    "Keningau",
    "Lahad Datu",
    "Semporna",
    "Beaufort",
    "Beluran",
    "Bongawan",
    "Inanam",
    "Kiansom",
    "Kota Belud",
    "Kota Kinabatangan",
    "Kota Marudu",
    "Kuala Penyu",
    "Kunak",
    "Likas",
    "Luyang",
    "Membakut",
    "Menumbok",
    "Nabawan",
    "Pamol",
    "Pitas",
    "Sipitang",
    "Tambunan",
    "Tamparuli",
    "Telipok",
    "Tenom",
    "Tuaran",
    "Telupid",
  ],
  Sarawak: [
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
    "Kota Samarahan",
    "Sri Aman",
    "Limbang",
    "Sarikei",
    "Mukah",
    "Asajaya",
    "Balingian",
    "Baram",
    "Bau",
    "Bekenu",
    "Belaga",
    "Belawai",
    "Betong",
    "Bintangor",
    "Dalat",
    "Daro",
    "Debak",
    "Engkilili",
    "Julau",
    "Kabong",
    "Kanowit",
    "Kapit",
    "Lawas",
    "Lingga",
    "Long Lama",
    "Lubok Antu",
    "Lundu",
    "Lutong",
    "Maradong",
    "Marudi",
    "Matu",
    "Nanga Medamit",
    "Niah",
    "Pusa",
    "Roban",
    "Saratok",
    "Sebauh",
    "Sebuyau",
    "Serian",
    "Simunjan",
    "Song",
    "Spaoh",
    "Sundar",
    "Tanjung Kidurong",
    "Tatau",
  ],
  Selangor: [
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "USJ",
    "Puchong",
    "Klang",
    "Kajang",
    "Cheras",
    "Ampang",
    "Cyberjaya",
    "Bangi",
    "Semenyih",
    "Rawang",
    "Sungai Buloh",
    "Damansara",
    "Kota Damansara",
    "Sepang",
    "Selayang",
    "Gombak",
    "Balakong",
    "Seri Kembangan",
    "Kuala Selangor",
    "Sabak Bernam",
    "Banting",
    "Kuala Langat",
    "Setia Alam",
    "Bandar Sunway",
    "Alam Impian",
    "Aman Perdana",
    "Ambang Botanic",
    "Ara Damansara",
    "Bandar Botanic",
    "Bandar Bukit Raja",
    "Bandar Bukit Tinggi",
    "Bandar Kinrara",
    "Bandar Mahkota Cheras",
    "Bandar Puteri Klang",
    "Bandar Puteri Puchong",
    "Bandar Saujana Putra",
    "Bandar Sri Damansara",
    "Bandar Sungai Long",
    "Bandar Utama",
    "Batang Berjuntai",
    "Batang Kali",
    "Batu Arang",
    "Batu Caves",
    "Beranang",
    "Bukit Antarabangsa",
    "Bukit Beruntung",
    "Bukit Jelutong",
    "Bukit Rahman Putra",
    "Bukit Rotan",
    "Bukit Subang",
    "Country Heights",
    "Damansara Damai",
    "Damansara Intan",
    "Damansara Jaya",
    "Damansara Kim",
    "Damansara Perdana",
    "Damansara Utama",
    "Denai Alam",
    "Dengkil",
    "Glenmarie",
    "Hulu Langat",
    "Hulu Selangor",
    "I-City",
    "Ijok",
    "Jade Hills",
    "Jenjarom",
    "Jeram",
    "Jugra",
    "Kalumpang",
    "Kapar",
    "Kayu Ara",
    "Kelana Jaya",
    "Kerling",
    "Kota Emerald",
    "Kota Kemuning",
    "Kuala Kubu Baru",
    "Kuang",
    "Kundang",
    "Mutiara Damansara",
    "Nilai",
    "Pandamaran",
    "Port Klang",
    "Puchong South",
    "Pulau Indah (Pulau Lumut)",
    "Pulau Carey",
    "Pulau Ketam",
    "Puncak Alam",
    "Puncak Jalil",
    "Putra Heights",
    "Rasa",
    "Salak Tinggi",
    "Saujana",
    "Saujana Utama",
    "Sekinchan",
    "Serdang",
    "Serendah",
    "Setia Eco Park",
    "Sierra Mas",
    "SS2",
    "Subang Bestari",
    "Subang Heights",
    "Subang Perdana",
    "Sungai Ayer Tawar",
    "Sungai Besar",
    "Sungai Gumut",
    "Sungai Panjang",
    "Sungai Pelek",
    "Taman TTDI Jaya",
    "Tanjong Duabelas",
    "Tanjong Karang",
    "Tanjong Sepat",
    "Telok Panglima Garang",
    "Tropicana",
    "Ulu Bernam",
    "Ulu Klang",
    "Ulu Yam",
    "USJ Heights",
    "Valencia",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Marang",
    "Besut",
    "Chukai",
    "Jerteh",
    "Banggul",
    "Binjai",
    "Bukit Payung",
    "Cabang Tiga",
    "Caluk",
    "Cenering",
    "Hulu Terengganu",
    "Kerteh",
    "Kijal",
    "Kuala Ibai",
    "Kuala Paka",
    "Paka",
    "Setiu",
    "Sura",
    "Kuala Nerus",
    "Teluk Kalung",
  ],
};

function isValidArea(state, area) {
  const options = AREAS_BY_STATE[state];
  return Boolean(options && options.includes(area));
}

module.exports = { AREAS_BY_STATE, isValidArea };
