// Structured area/town list, keyed by state - used to drive the dependent
// "Area" dropdown on both the Post Listing and Post Buyer Requirement forms.
//
// This replaces free-text area entry so the matching engine (utils/matching.js)
// can compare areas exactly instead of guessing via substring matching -
// "PJ" vs "Petaling Jaya" never lined up as text, but as two selections from
// the same list they now do.
//
// This is a best-effort list of well-known towns per state, not an
// exhaustive gazetteer. If an agent needs a town that's missing, add it to
// the array below for that state - no other code changes required.

const AREAS_BY_STATE = {
  Johor: [
    "Johor Bahru",
    "Iskandar Puteri",
    "Nusajaya",
    "Skudai",
    "Kulai",
    "Pasir Gudang",
    "Kluang",
    "Batu Pahat",
    "Muar",
    "Segamat",
    "Pontian",
    "Kota Tinggi",
    "Mersing",
    "Tangkak",
    "Gelang Patah",
    "Ulu Tiram",
  ],
  Kedah: [
    "Alor Setar",
    "Sungai Petani",
    "Kulim",
    "Langkawi",
    "Jitra",
    "Baling",
    "Kuala Kedah",
    "Gurun",
    "Pendang",
    "Yan",
    "Lunas",
    "Sik",
    "Mergong",
    "Sungai Kob",
    "Padang Serai",
  ],
  Kelantan: [
    "Kota Bharu",
    "Pasir Mas",
    "Tanah Merah",
    "Machang",
    "Gua Musang",
    "Tumpat",
    "Kuala Krai",
    "Wakaf Bharu",
    "Pasir Puteh",
  ],
  "Kuala Lumpur": [
    "Bangsar",
    "Mont Kiara",
    "Sri Hartamas",
    "Damansara Heights",
    "KLCC",
    "Bukit Bintang",
    "Cheras",
    "Setapak",
    "Wangsa Maju",
    "Titiwangsa",
    "Sentul",
    "Kepong",
    "Bukit Jalil",
    "Sri Petaling",
    "Taman Desa",
    "Segambut",
    "Ampang Hilir",
    "Pantai",
    "Bandar Tun Razak",
    "Jinjang",
    "OUG (Old Klang Road)",
  ],
  Labuan: ["Bandar Labuan", "Victoria", "Rancha-Rancha", "Patau-Patau"],
  Melaka: [
    "Bandar Melaka",
    "Ayer Keroh",
    "Alor Gajah",
    "Jasin",
    "Batu Berendam",
    "Bukit Katil",
    "Klebang",
    "Tanjung Kling",
    "Masjid Tanah",
  ],
  "Negeri Sembilan": [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Bahau",
    "Kuala Pilah",
    "Rembau",
    "Tampin",
    "Mantin",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Raub",
    "Jerantut",
    "Cameron Highlands",
    "Genting Highlands",
    "Mentakab",
    "Pekan",
    "Kuala Lipis",
  ],
  Perak: [
    "Ipoh",
    "Taiping",
    "Sitiawan",
    "Teluk Intan",
    "Lumut",
    "Batu Gajah",
    "Kampar",
    "Tapah",
    "Bidor",
    "Kuala Kangsar",
    "Manjung",
    "Gopeng",
    "Parit Buntar",
  ],
  Perlis: ["Kangar", "Arau", "Padang Besar", "Kuala Perlis"],
  "Pulau Pinang": [
    "George Town",
    "Bayan Lepas",
    "Bukit Mertajam",
    "Butterworth",
    "Sungai Ara",
    "Tanjung Bungah",
    "Batu Ferringhi",
    "Air Itam",
    "Gelugor",
    "Simpang Ampat",
    "Nibong Tebal",
    "Balik Pulau",
    "Jelutong",
    "Bayan Baru",
    "Tasek Gelugor",
  ],
  Putrajaya: [
    "Precinct 1",
    "Precinct 8",
    "Precinct 9",
    "Precinct 11",
    "Precinct 14",
    "Precinct 16",
    "Precinct 18",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Penampang",
    "Putatan",
    "Papar",
    "Kudat",
    "Ranau",
    "Keningau",
    "Lahad Datu",
    "Semporna",
  ],
  Sarawak: [
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
    "Kota Samarahan",
    "Sri Aman",
    "Limbang",
    "Sarikei",
    "Mukah",
  ],
  Selangor: [
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "USJ",
    "Puchong",
    "Klang",
    "Kajang",
    "Cheras",
    "Ampang",
    "Cyberjaya",
    "Bangi",
    "Semenyih",
    "Rawang",
    "Sungai Buloh",
    "Damansara",
    "Kota Damansara",
    "Sepang",
    "Selayang",
    "Gombak",
    "Balakong",
    "Seri Kembangan",
    "Kuala Selangor",
    "Sabak Bernam",
    "Banting",
    "Kuala Langat",
    "Setia Alam",
    "Bandar Sunway",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Marang",
    "Besut",
    "Chukai",
    "Jerteh",
  ],
};

function isValidArea(state, area) {
  const options = AREAS_BY_STATE[state];
  return Boolean(options && options.includes(area));
}

module.exports = { AREAS_BY_STATE, isValidArea };
